"""Deterministic evidence normalization, classification, and reporting."""

from reconcile.evidence.admission import (
    EvidenceAttempt,
    EvidencePipeline,
    ProbeRun,
)
from reconcile.evidence.classification import CoreEvaluation, evaluate_evidence
from reconcile.evidence.engine import EvidenceEngine
from reconcile.evidence.recovery_rules import (
    CLOUD_RUN_SERVICE_TARGET_KIND,
    CREATE_FIRESTORE_RELEASE_RECORD_PROFILE,
    CREATE_FIRESTORE_RELEASE_RECORD_PROFILE_VERSION,
    FIRESTORE_DOCUMENT_TARGET_KIND,
    PROMOTE_CLOUD_RUN_TRAFFIC_PROFILE,
    PROMOTE_CLOUD_RUN_TRAFFIC_PROFILE_VERSION,
    RECOVERY_ACTION_PROFILE_VERSION,
    RECOVERY_ACTION_PROFILES,
    RECOVERY_CAPABILITY_VERSION,
    RECOVERY_TOOL_VERSION,
    STAGE_CLOUD_RUN_REVISION_PROFILE,
    STAGE_CLOUD_RUN_REVISION_PROFILE_VERSION,
    RecoveryActionProfile,
    RecoveryCapability,
    RecoveryPreconditionKind,
    RecoveryRuleViolation,
    recovery_precondition_sha256,
    resolve_recovery_action_profile,
    validate_recovery_action,
    validate_recovery_evidence,
    validate_recovery_proof,
)
from reconcile.evidence.recovery_verification import (
    RECOVERY_CHAIN_PROFILE_VERSION,
    RECOVERY_CORRELATION_POLICY_VERSION,
    RECOVERY_FRESHNESS_POLICY_VERSION,
    RECOVERY_VERIFIER_VERSION,
    RecoveryVerificationError,
    RecoveryVerificationResult,
    verify_recovery,
)
from reconcile.evidence.reporting import build_report
from reconcile.evidence.rules import (
    DuplicateTargetRule,
    RuleInput,
    RuleObservation,
    RuleRejected,
    RuleRequest,
    RuleVerdict,
    TargetNormalizer,
    TargetRuleDescriptor,
    TargetRuleRegistration,
    TargetRuleRegistry,
    TargetRuleRegistryFrozen,
)

__all__ = [
    "CLOUD_RUN_SERVICE_TARGET_KIND",
    "CREATE_FIRESTORE_RELEASE_RECORD_PROFILE",
    "CREATE_FIRESTORE_RELEASE_RECORD_PROFILE_VERSION",
    "FIRESTORE_DOCUMENT_TARGET_KIND",
    "PROMOTE_CLOUD_RUN_TRAFFIC_PROFILE",
    "PROMOTE_CLOUD_RUN_TRAFFIC_PROFILE_VERSION",
    "RECOVERY_ACTION_PROFILES",
    "RECOVERY_ACTION_PROFILE_VERSION",
    "RECOVERY_CAPABILITY_VERSION",
    "RECOVERY_CHAIN_PROFILE_VERSION",
    "RECOVERY_CORRELATION_POLICY_VERSION",
    "RECOVERY_FRESHNESS_POLICY_VERSION",
    "RECOVERY_TOOL_VERSION",
    "RECOVERY_VERIFIER_VERSION",
    "STAGE_CLOUD_RUN_REVISION_PROFILE",
    "STAGE_CLOUD_RUN_REVISION_PROFILE_VERSION",
    "CoreEvaluation",
    "DuplicateTargetRule",
    "EvidenceAttempt",
    "EvidenceEngine",
    "EvidencePipeline",
    "ProbeRun",
    "RecoveryActionProfile",
    "RecoveryCapability",
    "RecoveryPreconditionKind",
    "RecoveryRuleViolation",
    "RecoveryVerificationError",
    "RecoveryVerificationResult",
    "RuleInput",
    "RuleObservation",
    "RuleRejected",
    "RuleRequest",
    "RuleVerdict",
    "TargetNormalizer",
    "TargetRuleDescriptor",
    "TargetRuleRegistration",
    "TargetRuleRegistry",
    "TargetRuleRegistryFrozen",
    "build_report",
    "evaluate_evidence",
    "recovery_precondition_sha256",
    "resolve_recovery_action_profile",
    "validate_recovery_action",
    "validate_recovery_evidence",
    "validate_recovery_proof",
    "verify_recovery",
]
