#!/usr/bin/env python3
"""Focused, local acceptance for the documentation and demo package."""

from __future__ import annotations

import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

from replay_gate_g5r import EvidenceError, load_and_validate

ROOT = Path(__file__).resolve().parents[1]
REQUIRED = (
    ROOT / "README.md",
    ROOT / "docs" / "architecture.dot",
    ROOT / "docs" / "architecture.png",
    ROOT / "docs" / "architecture.svg",
    ROOT / "docs" / "claims-and-limitations.md",
    ROOT / "docs" / "hosted-runbook.md",
    ROOT / "demo" / "README.md",
    ROOT / "demo" / "script.md",
    ROOT / "demo" / "proof.dot",
    ROOT / "demo" / "proof.svg",
    ROOT / "demo" / "evidence" / "proof-to-permit.json",
)
MARKDOWN = tuple(path for path in REQUIRED if path.suffix == ".md")
LINK = re.compile(r"!?(?:\[[^]]*\])\(([^)]+)\)")
PRIVATE_PATH = re.compile(r"(?:/home/|/Users/|file://|[A-Za-z]:\\\\Users\\\\)")
FORBIDDEN_CLAIMS = (
    re.compile(
        r"\bgemini\s+(?:proved|proves|decided|decides|authorized|authorizes)\b", re.I
    ),
    re.compile(r"\badaptive\s+(?:beat|beats|outperformed|outperforms)\b", re.I),
)


class CandidateError(ValueError):
    """The release-ready documentation or demo contract failed."""


def _require(condition: bool, message: str) -> None:
    if not condition:
        raise CandidateError(message)


def _check_files() -> None:
    missing = [str(path.relative_to(ROOT)) for path in REQUIRED if not path.is_file()]
    _require(not missing, "missing required files: " + ", ".join(missing))


def _target_from_markdown(raw: str) -> str:
    target = raw.strip()
    if target.startswith("<") and ">" in target:
        target = target[1 : target.index(">")]
    elif " " in target:
        target = target.split(" ", 1)[0]
    return target


def _check_links_and_paths() -> int:
    checked = 0
    for document in MARKDOWN:
        text = document.read_text(encoding="utf-8")
        _require(
            PRIVATE_PATH.search(text) is None,
            f"private path in {document.relative_to(ROOT)}",
        )
        for pattern in FORBIDDEN_CLAIMS:
            _require(
                pattern.search(text) is None,
                f"forbidden claim in {document.relative_to(ROOT)}: {pattern.pattern}",
            )
        for match in LINK.finditer(text):
            target = _target_from_markdown(match.group(1))
            if not target or target.startswith(("#", "http://", "https://", "mailto:")):
                continue
            relative = target.split("#", 1)[0]
            resolved = (document.parent / relative).resolve()
            _require(
                resolved == ROOT or ROOT in resolved.parents,
                f"link escapes repository: {target}",
            )
            _require(
                resolved.exists(),
                f"broken link in {document.relative_to(ROOT)}: {target}",
            )
            checked += 1
    return checked


def _check_claim_markers() -> None:
    readme = (ROOT / "README.md").read_text(encoding="utf-8")
    claims = (ROOT / "docs" / "claims-and-limitations.md").read_text(encoding="utf-8")
    _require(
        "Gemini investigates. Deterministic evidence decides." in readme,
        "authority shorthand is missing",
    )
    _require(
        "It did not authorize adaptive-efficiency" in readme,
        "README efficiency boundary is missing",
    )
    _require("No general exactly-once guarantee" in claims, "non-claim is missing")
    _require(
        "does not depend on a public endpoint" in readme,
        "durable endpoint limitation is missing",
    )


def _check_demo_duration() -> int:
    script = (ROOT / "demo" / "script.md").read_text(encoding="utf-8")
    match = re.search(r"<!--\s*duration-seconds:\s*(\d+)\s*-->", script)
    _require(match is not None, "demo duration marker is missing")
    duration = int(match.group(1))
    _require(1 <= duration <= 240, "demo candidate exceeds four minutes")
    return duration


def _check_graphviz() -> str:
    executable = shutil.which("dot")
    if executable is None:
        for svg in (ROOT / "docs" / "architecture.svg", ROOT / "demo" / "proof.svg"):
            text = svg.read_text(encoding="utf-8")
            _require(
                "<svg" in text and "Generated by graphviz" in text, f"invalid {svg}"
            )
        png = (ROOT / "docs" / "architecture.png").read_bytes()
        _require(png.startswith(b"\x89PNG\r\n\x1a\n"), "invalid architecture PNG")
        return "exported diagram structure checked (Graphviz unavailable)"

    with tempfile.TemporaryDirectory(prefix="reconcile-diagram-check-") as directory:
        temporary = Path(directory)
        for source, export, output_format in (
            (
                ROOT / "docs" / "architecture.dot",
                ROOT / "docs" / "architecture.svg",
                "svg",
            ),
            (
                ROOT / "docs" / "architecture.dot",
                ROOT / "docs" / "architecture.png",
                "png",
            ),
            (ROOT / "demo" / "proof.dot", ROOT / "demo" / "proof.svg", "svg"),
        ):
            rendered = temporary / export.name
            subprocess.run(
                [executable, f"-T{output_format}", str(source), "-o", str(rendered)],
                check=True,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.PIPE,
            )
            _require(
                rendered.read_bytes() == export.read_bytes(),
                f"stale SVG export: {export.relative_to(ROOT)}",
            )
    return "Graphviz source/export parity checked"


def main() -> int:
    try:
        _check_files()
        load_and_validate(ROOT / "demo" / "evidence" / "proof-to-permit.json")
        link_count = _check_links_and_paths()
        _check_claim_markers()
        duration = _check_demo_duration()
        diagram_result = _check_graphviz()
    except (
        CandidateError,
        EvidenceError,
        OSError,
        subprocess.SubprocessError,
    ) as error:
        print(f"FAIL: {error}", file=sys.stderr)
        return 1

    print("RECONCILE documentation/demo package: PASS")
    print("  accepted evidence invariants: checked")
    print(f"  local documentation links: {link_count} checked")
    print("  private paths and frozen claims: checked")
    print(f"  demo duration: {duration}s (limit 240s)")
    print(f"  diagrams: {diagram_result}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
